services:
  whisper:
    image: jmgirard/wsl-cuda-whisper:${VAD_TAG}
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=pass
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["/bin/bash", "-c", "/setup_scripts/install_whisper.sh && exec /init"]
    command: []
